name: Render Citations

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML with Citations
        run: |
          pandoc -s README.md --bibliography=data/citations.bib -o output.html

      - name: Upload Rendered Output
        uses: actions/upload-artifact@v3
        with:
          name: rendered-output
          path: output.html
